swagger: "2.0"
info:
  description: "akaCampaign swagger."
  version: "1.0.0"
  title: "akaCampaign"
  contact:
    email: ""
  license:
    name: "Private license"
    url: ""
host: "localhost:8081"
basePath: "/api/v1"
tags:
  - name: "hello"
    description: "Simple hello"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
schemes:
  - "http"
paths:
  /hello:
    get:
      tags:
        - "hello"
      summary: "Hello message"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
  /user:
    post:
      parameters:
        - in: body
          name: "name"
          schema:
            $ref: "#/definitions/User"
      summary: "Create user api"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        default:
          description: Unexpected error
definitions:
  Hello:
    type: object
    properties:
      title:
        type: string
      message:
        type: string
  User:
    type: "object"
    properties:
      id:
        type: number
      name:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
      role_id:
        type: number
    required:
      - name
      - email
      - password
      - roleId
